//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibsClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVelibsService")]
    public interface IVelibsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/GetContracts", ReplyAction="http://tempuri.org/IVelibsService/GetContractsResponse")]
        VelibsIntermediary.CompositeContract[] GetContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/GetContracts", ReplyAction="http://tempuri.org/IVelibsService/GetContractsResponse")]
        System.Threading.Tasks.Task<VelibsIntermediary.CompositeContract[]> GetContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/GetContract", ReplyAction="http://tempuri.org/IVelibsService/GetContractResponse")]
        VelibsIntermediary.CompositeStation[] GetContract(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/GetContract", ReplyAction="http://tempuri.org/IVelibsService/GetContractResponse")]
        System.Threading.Tasks.Task<VelibsIntermediary.CompositeStation[]> GetContractAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/GetStation", ReplyAction="http://tempuri.org/IVelibsService/GetStationResponse")]
        VelibsIntermediary.CompositeStation GetStation(string city, int station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/GetStation", ReplyAction="http://tempuri.org/IVelibsService/GetStationResponse")]
        System.Threading.Tasks.Task<VelibsIntermediary.CompositeStation> GetStationAsync(string city, int station);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibsServiceChannel : VelibsClient.ServiceReference1.IVelibsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibsServiceClient : System.ServiceModel.ClientBase<VelibsClient.ServiceReference1.IVelibsService>, VelibsClient.ServiceReference1.IVelibsService {
        
        public VelibsServiceClient() {
        }
        
        public VelibsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VelibsIntermediary.CompositeContract[] GetContracts() {
            return base.Channel.GetContracts();
        }
        
        public System.Threading.Tasks.Task<VelibsIntermediary.CompositeContract[]> GetContractsAsync() {
            return base.Channel.GetContractsAsync();
        }
        
        public VelibsIntermediary.CompositeStation[] GetContract(string city) {
            return base.Channel.GetContract(city);
        }
        
        public System.Threading.Tasks.Task<VelibsIntermediary.CompositeStation[]> GetContractAsync(string city) {
            return base.Channel.GetContractAsync(city);
        }
        
        public VelibsIntermediary.CompositeStation GetStation(string city, int station) {
            return base.Channel.GetStation(city, station);
        }
        
        public System.Threading.Tasks.Task<VelibsIntermediary.CompositeStation> GetStationAsync(string city, int station) {
            return base.Channel.GetStationAsync(city, station);
        }
    }
}
