//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.VelibsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeStation", Namespace="http://schemas.datacontract.org/2004/07/VelibsLib")]
    [System.SerializableAttribute()]
    public partial class CompositeStation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Available_Bike_StandsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Available_BikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Bike_StandsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Contract_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Last_UpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.VelibsServiceReference.Position PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Available_Bike_Stands {
            get {
                return this.Available_Bike_StandsField;
            }
            set {
                if ((this.Available_Bike_StandsField.Equals(value) != true)) {
                    this.Available_Bike_StandsField = value;
                    this.RaisePropertyChanged("Available_Bike_Stands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Available_Bikes {
            get {
                return this.Available_BikesField;
            }
            set {
                if ((this.Available_BikesField.Equals(value) != true)) {
                    this.Available_BikesField = value;
                    this.RaisePropertyChanged("Available_Bikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Banking {
            get {
                return this.BankingField;
            }
            set {
                if ((this.BankingField.Equals(value) != true)) {
                    this.BankingField = value;
                    this.RaisePropertyChanged("Banking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bike_Stands {
            get {
                return this.Bike_StandsField;
            }
            set {
                if ((this.Bike_StandsField.Equals(value) != true)) {
                    this.Bike_StandsField = value;
                    this.RaisePropertyChanged("Bike_Stands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Bonus {
            get {
                return this.BonusField;
            }
            set {
                if ((this.BonusField.Equals(value) != true)) {
                    this.BonusField = value;
                    this.RaisePropertyChanged("Bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contract_Name {
            get {
                return this.Contract_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Contract_NameField, value) != true)) {
                    this.Contract_NameField = value;
                    this.RaisePropertyChanged("Contract_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.VelibsServiceReference.Position Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/VelibsLib")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LngField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lat {
            get {
                return this.LatField;
            }
            set {
                if ((this.LatField.Equals(value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lng {
            get {
                return this.LngField;
            }
            set {
                if ((this.LngField.Equals(value) != true)) {
                    this.LngField = value;
                    this.RaisePropertyChanged("Lng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibsServiceReference.IVelibsService", CallbackContract=typeof(ConsoleApp1.VelibsServiceReference.IVelibsServiceCallback))]
    public interface IVelibsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/GetContract", ReplyAction="http://tempuri.org/IVelibsService/GetContractResponse")]
        void GetContract(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/GetContract", ReplyAction="http://tempuri.org/IVelibsService/GetContractResponse")]
        System.Threading.Tasks.Task GetContractAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/GetStation", ReplyAction="http://tempuri.org/IVelibsService/GetStationResponse")]
        void GetStation(string city, int station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/GetStation", ReplyAction="http://tempuri.org/IVelibsService/GetStationResponse")]
        System.Threading.Tasks.Task GetStationAsync(string city, int station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/SubscribeGetContractEvent", ReplyAction="http://tempuri.org/IVelibsService/SubscribeGetContractEventResponse")]
        void SubscribeGetContractEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/SubscribeGetContractEvent", ReplyAction="http://tempuri.org/IVelibsService/SubscribeGetContractEventResponse")]
        System.Threading.Tasks.Task SubscribeGetContractEventAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/SubscribeGetContractFinishedEvent", ReplyAction="http://tempuri.org/IVelibsService/SubscribeGetContractFinishedEventResponse")]
        void SubscribeGetContractFinishedEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/SubscribeGetContractFinishedEvent", ReplyAction="http://tempuri.org/IVelibsService/SubscribeGetContractFinishedEventResponse")]
        System.Threading.Tasks.Task SubscribeGetContractFinishedEventAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/SubscribeGetStationEvent", ReplyAction="http://tempuri.org/IVelibsService/SubscribeGetStationEventResponse")]
        void SubscribeGetStationEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/SubscribeGetStationEvent", ReplyAction="http://tempuri.org/IVelibsService/SubscribeGetStationEventResponse")]
        System.Threading.Tasks.Task SubscribeGetStationEventAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/SubscribeGetStationFinishedEvent", ReplyAction="http://tempuri.org/IVelibsService/SubscribeGetStationFinishedEventResponse")]
        void SubscribeGetStationFinishedEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsService/SubscribeGetStationFinishedEvent", ReplyAction="http://tempuri.org/IVelibsService/SubscribeGetStationFinishedEventResponse")]
        System.Threading.Tasks.Task SubscribeGetStationFinishedEventAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibsServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibsService/GotContract")]
        void GotContract(string city, ConsoleApp1.VelibsServiceReference.CompositeStation[] result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibsService/GetContractFinished")]
        void GetContractFinished();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibsService/GotStation")]
        void GotStation(string city, int station, ConsoleApp1.VelibsServiceReference.CompositeStation result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibsService/GetStationFinished")]
        void GetStationFinished();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibsServiceChannel : ConsoleApp1.VelibsServiceReference.IVelibsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibsServiceClient : System.ServiceModel.DuplexClientBase<ConsoleApp1.VelibsServiceReference.IVelibsService>, ConsoleApp1.VelibsServiceReference.IVelibsService {
        
        public VelibsServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public VelibsServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public VelibsServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibsServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibsServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetContract(string city) {
            base.Channel.GetContract(city);
        }
        
        public System.Threading.Tasks.Task GetContractAsync(string city) {
            return base.Channel.GetContractAsync(city);
        }
        
        public void GetStation(string city, int station) {
            base.Channel.GetStation(city, station);
        }
        
        public System.Threading.Tasks.Task GetStationAsync(string city, int station) {
            return base.Channel.GetStationAsync(city, station);
        }
        
        public void SubscribeGetContractEvent() {
            base.Channel.SubscribeGetContractEvent();
        }
        
        public System.Threading.Tasks.Task SubscribeGetContractEventAsync() {
            return base.Channel.SubscribeGetContractEventAsync();
        }
        
        public void SubscribeGetContractFinishedEvent() {
            base.Channel.SubscribeGetContractFinishedEvent();
        }
        
        public System.Threading.Tasks.Task SubscribeGetContractFinishedEventAsync() {
            return base.Channel.SubscribeGetContractFinishedEventAsync();
        }
        
        public void SubscribeGetStationEvent() {
            base.Channel.SubscribeGetStationEvent();
        }
        
        public System.Threading.Tasks.Task SubscribeGetStationEventAsync() {
            return base.Channel.SubscribeGetStationEventAsync();
        }
        
        public void SubscribeGetStationFinishedEvent() {
            base.Channel.SubscribeGetStationFinishedEvent();
        }
        
        public System.Threading.Tasks.Task SubscribeGetStationFinishedEventAsync() {
            return base.Channel.SubscribeGetStationFinishedEventAsync();
        }
    }
}
